# Generated by Django 6.0.2 on 2026-03-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='Account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='GST_number',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='restaurant_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
