# Generated by Django 6.0.2 on 2026-04-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_max_out',
            field=models.DateTimeField(blank=True, max_length=2, null=True),
        ),
    ]
