# Generated by Django 6.0.2 on 2026-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
