# Generated by Django 6.0.2 on 2026-04-17 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_otp_max_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be 10 digits only', regex='^(\\+\\d{1,3})?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to='users/'),
        ),
    ]
