# Generated by Django 6.0.2 on 2026-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendorprofile_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='Account_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='GST_number',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='restaurant_address',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='restaurant_description',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='resturant_pic',
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='assests/users/default_user.png', null=True, upload_to='assets/users/'),
        ),
    ]
