# Generated by Django 6.0.2 on 2026-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_approved_vendorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='asseste/delivery/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='assests/vendor/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='assests/customers/'),
        ),
    ]
