# Generated by Django 6.0.2 on 2026-07-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('HOME', 'home'), ('OFFICE', 'office')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(default='Haryana', max_length=100),
            preserve_default=False,
        ),
    ]
