# Generated by Django 6.0.2 on 2026-02-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deliveryprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='assests/delivery/'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
