# Generated by Django 6.0.2 on 2026-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_deliveryprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='assests/users/default_user.png', null=True, upload_to='assests/users/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='resturant_pic',
            field=models.ImageField(blank=True, null=True, upload_to='assests/resturants/'),
        ),
    ]
