# Generated by Django 6.0.2 on 2026-03-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customerprofile_address_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='user',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customerprofile'),
            preserve_default=False,
        ),
    ]
