# Generated by Django 6.0.2 on 2026-03-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON-VEG', 'Non-Vegetarian'), ('EGG', 'Contains Egg')], default='VEG', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('preparation_time', models.IntegerField(default=20, help_text='In minutes')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='restaurants.category')),
            ],
        ),
    ]
