# Generated by Django 6.0.2 on 2026-03-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_vendorprofile_account_number_and_more'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/restaurants/product_images/'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_pic', models.ImageField(blank=True, null=True, upload_to='assets/restaurants/')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('contact_number', models.CharField(max_length=10)),
                ('restaurant_description', models.TextField(blank=True, null=True)),
                ('GST_number', models.CharField(max_length=100)),
                ('Account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fassai_certificate', models.ImageField(upload_to='assets/restaurants/certificate/')),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='accounts.vendorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.restaurant'),
        ),
    ]
