# Generated by Django 6.0.2 on 2026-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static\\categories\\Gemini_Generated_Image_azqgrtazqgrtazqg.png', upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fassai_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/certificate/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='resturant_pic',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
