# Generated by Django 6.0.2 on 2026-03-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_vendorprofile_account_number_and_more'),
        ('restaurants', '0003_product_size_alter_product_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='fassai_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='assets/restaurants/certificate/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='accounts.vendorprofile'),
        ),
    ]
